CREATE TABLE PopulationData ( Population VARCHAR(255) PRIMARY KEY, SuperPopulation VARCHAR(255) ); 

CREATE TABLE SampleData ( SAMPLE_ID INT PRIMARY KEY, Population VARCHAR(255), FOREIGN KEY (Population) REFERENCES PopulationData(Population) );

CREATE TABLE SNPData ( SNP_ID VARCHAR(255) PRIMARY KEY, GENE_NAME VARCHAR(255), CHROMOSOMAL_POSITION INT );

CREATE TABLE ClinicalRelevanceData (
    SNP_ID VARCHAR(255),
    ClinicalTraits VARCHAR(255),
    PRIMARY KEY (SNP_ID, ClinicalTraits),
    FOREIGN KEY (SNP_ID) REFERENCES SNPData(SNP_ID)
);

CREATE TABLE GenotypeData (
    SAMPLE_ID INT,
    SNP_ID VARCHAR(255),
    Genotype VARCHAR(255),
    GenotypeFrequency FLOAT,
    PRIMARY KEY (SAMPLE_ID, SNP_ID, Genotype),
    FOREIGN KEY (SAMPLE_ID) REFERENCES SampleData(SAMPLE_ID),
    FOREIGN KEY (SNP_ID) REFERENCES SNPData(SNP_ID)
);

CREATE TABLE VariantData (
    SAMPLE_ID INT,
    SNP_ID VARCHAR(255),
    AlleleFrequency FLOAT,
    PRIMARY KEY (SAMPLE_ID, SNP_ID),
    FOREIGN KEY (SAMPLE_ID) REFERENCES SampleData(SAMPLE_ID),
    FOREIGN KEY (SNP_ID) REFERENCES SNPData(SNP_ID)
);
