"""Updated GENE_NAME to GENE

Revision ID: c2400528aca4
Revises: 
Create Date: 2024-02-08 00:56:26.473295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2400528aca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PopulationData')
    op.drop_table('SNPData')
    op.drop_table('ClinicalRelevanceData')
    op.drop_table('SampleData')
    op.drop_table('GenotypeData')
    op.drop_table('VariantData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VariantData',
    sa.Column('SAMPLE_ID', sa.TEXT(), nullable=False),
    sa.Column('SNP_ID', sa.VARCHAR(length=255), nullable=False),
    sa.Column('AlleleFrequency', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['SNP_ID'], ['SNPData.SNP_ID'], ),
    sa.PrimaryKeyConstraint('SAMPLE_ID', 'SNP_ID')
    )
    op.create_table('GenotypeData',
    sa.Column('SAMPLE_ID', sa.TEXT(), nullable=False),
    sa.Column('SNP_ID', sa.VARCHAR(length=255), nullable=False),
    sa.Column('Genotype', sa.VARCHAR(length=255), nullable=False),
    sa.Column('GenotypeFrequency', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['SNP_ID'], ['ClinicalRelevanceData.SNP_ID'], ),
    sa.PrimaryKeyConstraint('SAMPLE_ID', 'SNP_ID', 'Genotype')
    )
    op.create_table('SampleData',
    sa.Column('SAMPLE_ID', sa.TEXT(), nullable=False),
    sa.Column('Population', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['Population'], ['PopulationData.Population'], ),
    sa.PrimaryKeyConstraint('SAMPLE_ID')
    )
    op.create_table('ClinicalRelevanceData',
    sa.Column('SNP_ID', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ClinicalTraits', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('SNP_ID', 'ClinicalTraits')
    )
    op.create_table('SNPData',
    sa.Column('SNP_ID', sa.VARCHAR(length=255), nullable=False),
    sa.Column('GENE_NAME', sa.VARCHAR(length=255), nullable=True),
    sa.Column('CHROMOSOMAL_POSITION', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('SNP_ID')
    )
    op.create_table('PopulationData',
    sa.Column('Population', sa.VARCHAR(length=255), nullable=False),
    sa.Column('SuperPopulation', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Population')
    )
    # ### end Alembic commands ###
