CREATE INDEX idx_admixture_sample ON AdmixtureAnalysis(SampleID)
CREATE INDEX idx_clustering_sample ON ClusteringAnalysis(SampleID)
CREATE INDEX idx_genes ON SNPData(Genes)
CREATE INDEX idx_population ON SamplePopulation(Population)
CREATE INDEX idx_sample_id ON SampleData(SampleID)
CREATE INDEX idx_sample_snp ON SampleData(SNP_ID)
CREATE INDEX idx_snp_id ON SNPData(SNP_ID)
CREATE INDEX idx_super_population ON SamplePopulation(SuperPopulation)
CREATE INDEX idx_ALT_Freq ON SamplePopulation (ALT_Freq)
CREATE INDEX idx_GTFreq_00 ON SamplePopulation (GTFreq_00)
CREATE INDEX idx_GTFreq_01 ON SamplePopulation (GTFreq_01)
CREATE INDEX idx_GTFreq_11 ON SamplePopulation (GTFreq_11)
CREATE INDEX idx_REF_Freq ON SamplePopulation (REF_Freq)
CREATE INDEX idx_sampleid ON SamplePopulation(SampleID)
CREATE INDEX idx_avg_alt_freq ON SamplePopulation(avgALT_Freq)
CREATE INDEX idx_avg_ref_freq ON SamplePopulation(avgREF_Freq)
CREATE INDEX idx_chr_number ON SNPData(Chromosome_Number)
CREATE INDEX idx_chr_position ON SNPData(Chromosome_Position)
